settings:
    log_directory: .
    ip_list_directory: ./ip_lists
    log:
        cleanup_by_time:
            enabled: false
            mode: days
            value: 7
        cleanup_by_lines:
            enabled: true
            retain_lines: 10
        cleanup_by_rule:
            ceshi2:
                enabled: false
                retain_lines: 1000
            ceshi3:
                enabled: false
                retain_lines: 1000
            ceshi5:
                enabled: false
                retain_lines: 1000
            ceshi8:
                enabled: false
                retain_lines: 1000
            test-all:
                enabled: false
                retain_lines: 1000
            test-tcp01:
                enabled: false
                retain_lines: 1000
            测试:
                enabled: false
                retain_lines: 1000
            测试1:
                enabled: false
                retain_lines: 1000
            测试4:
                enabled: false
                retain_lines: 1000
            端口转发:
                enabled: false
                retain_lines: 1000
global_access_control:
    mode: priority
    whitelist_enabled: true
    whitelist_list_name: 全局白名单
    blacklist_enabled: true
    blacklist_list_name: 全局黑名单
ip_lists:
    whitelists:
        全局白名单:
            - 192.168.122.251
    blacklists:
        全局黑名单:
            - 2.2.2.2
    ip_sets:
        ipv:
            - 192.168.122.250
    country_ip_lists:
        中国ip:
            type: country
            source: CN
    url_ip_sets:
        vn:
            type: url
            source: https://raw.githubusercontent.com/mayaxcn/china-ip-list/refs/heads/master/chn_ip.txt
rules:
    - name: test-all
      protocol: tcp,udp
      listen_addr: 0.0.0.0
      listen_port: 22226
      forward_addr: 192.168.122.250
      forward_port: 3389
      access_control:
        mode: disabled
        list_name: 全局白名单
      enabled: true
      rate_limit: 1
      connection_limit: 1
web_services:
    - name: test-web
      enabled: true
      listen_ipv4: true
      listen_ipv6: true
      listen_addr: ""
      listen_port: 443
      access_control:
        mode: disabled
        list_name: 全局白名单
      security:
        block_on_404_count: 0
        block_on_block_count: 0
      tls:
        enabled: true
        min_version: TLS1.3
        http3_enabled: false
        ech_enabled: false
      apply_to_sub_rules: false
      limits:
        rule_rate_limit:
            send_speed_kbps: 0
            receive_speed_kbps: 0
        connection_rate_limit:
            send_speed_kbps: 0
            receive_speed_kbps: 0
        ip_rate_limit:
            send_speed_kbps: 0
            receive_speed_kbps: 0
        ip_connection_limit: 0
      unmatched_request:
        action: not_found
      sub_rules:
        - name: cnyun.de
          enabled: true
          service_type: reverse_proxy
          frontend_address: cnyun.de
          backend:
            address: http://192.168.122.49:8090
            ignore_tls_cert: false
            use_target_host_header: false
            grpc_secure: false
            disable_keep_alives: false
          redirect_url: ""
          coraza_waf: gf_simple_admin不允许
          security:
            block_on_404_count: 0
            block_on_coraza_count: 0
          network:
            disable_connection_reuse: false
            network_type: tcp
            http_client_timeout_sec: 30
          client_ip:
            from_header: false
            from_header_name: X-Forwarded-For
            add_to_header: false
            add_to_header_name: X-Forwarded-For
            add_proto_to_header: false
            add_proto_to_header_name: X-Forwarded-Proto
            add_host_to_header: false
            add_host_to_header_name: X-Forwarded-Host
          forwarded_headers:
            enabled: true
          cors_enabled: false
          auth:
            enabled: false
            username: ""
            password: ""
          ip_filter:
            mode: disabled
            list_name: 全局白名单
          user_agent_filter:
            mode: disabled
            list: []
          custom_robot_txt: ""
          force_https: false
          limits:
            rule_rate_limit:
                send_speed_kbps: 0
                receive_speed_kbps: 0
            connection_rate_limit:
                send_speed_kbps: 0
                receive_speed_kbps: 0
            ip_rate_limit:
                send_speed_kbps: 0
                receive_speed_kbps: 0
            ip_connection_limit: 0
tls:
    enabled: true
    cert_directory: ./certs
    manual: []
    acme:
        enabled: true
        accounts:
            - name: test
              provider: cloudflare
              email: 5615151651@qq.com
              cloudflare:
                email: ""
                api_key: ""
                api_token: JUTA22H-J14t8YU3R1v5ovW3LLBg0Dfs53dfcMCP
              domains:
                - cnyun.de
waf:
    enabled: true
    default_action: phase:2,deny,status:200
    rule_sets:
        - name: "1"
          source: inline
          path: ""
          rules:
            - |
              SecRule ARGS "@rx (?i)union.+select" "id:1001,phase:2,msg:'Basic SQL Injection Attack Detected'"
        - name: "2"
          source: inline
          path: ""
          rules:
            - SecRule ARGS "@rx (?i)<script.*>" "id:1002,phase:2,block,msg:'Basic XSS Attack Detected'"
        - name: "3"
          source: inline
          path: ""
          rules:
            - SecRule ARGS:testwaf "@streq block" "id:1001,phase:2,block,msg:'WAF Test - Blocked by URL Parameter Rule'"
        - name: "4"
          source: inline
          path: ""
          rules:
            - SecRule REQUEST_URI "@beginsWith /admin" "id:1002,phase:1,deny,status:404,msg:'Access to admin directory is forbidden'"
        - name: "5"
          source: inline
          path: ""
          rules:
            - |
              SecRule ARGS:testwaf "@contains block" "id:101,phase:2,deny,status:403,msg:'WAF Test Block Rule Triggered'"
        - name: gf_simple_123
          source: inline
          path: ""
          rules:
            - SecAction "id:35664,phase:1,nolog,pass,setvar:tx.ratelimit_count_123=0"
            - SecRule REQUEST_URI ".*" "id:35665,phase:2,nolog,pass,setvar:tx.ratelimit_count_123=+1,expirevar:tx.ratelimit_count_123=60"
            - 'SecRule TX:ratelimit_count_123 "@gt 2" "id:35666,phase:2,deny,status:429,log,msg:''Simple Rule: Rate limit of 2/60s exceeded for *. Blocking for 300s.''"'
        - name: aaaaaa
          source: url
          path: https://raw.githubusercontent.com/coreruleset/coreruleset/refs/heads/main/rules/RESPONSE-980-CORRELATION.conf
          rules:
            - ""
        - name: bbbbbb
          source: url
          path: https://raw.githubusercontent.com/coreruleset/coreruleset/refs/heads/main/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
          rules:
            - ""
        - name: "33333333333"
          source: inline
          path: ""
          rules:
            - |
              # 初始化全局计数器（按 IP 拼接 key）
              SecAction "id:1000,phase:1,nolog,pass"

              # 每次访问，累加计数
              SecRule REQUEST_HEADERS:Host "@rx .*" \
                "id:1001,phase:2,pass,nolog,chain,setvar:tx.ratelimit_%{REMOTE_ADDR}=+1,expirevar:tx.ratelimit_%{REMOTE_ADDR}=60"
                SecRule TX:ratelimit_%{REMOTE_ADDR} "@gt 2" \
                  "phase:2,log,deny,status:429,msg:'Rate limit exceeded from %{REMOTE_ADDR}'"
        - name: gf_simple_99999
          source: inline
          path: ""
          rules:
            - SecAction "id:1539,phase:1,nolog,pass,initcol:ip=%{REMOTE_ADDR}"
            - SecRule IP:BLOCKED_1539 "@eq 1" "id:1540,phase:1,deny,status:403,log,msg:'IP %{REMOTE_ADDR} blocked for *'"
            - SecRule REQUEST_URI "@rx ^.*$" "id:1541,phase:2,nolog,pass,setvar:ip.ratelimit_count_1539=+1,expirevar:ip.ratelimit_count_1539=60"
            - SecRule IP:ratelimit_count_1539 "@gt 2" "id:1542,phase:2,log,deny,status:429,setvar:IP.BLOCKED_1539=1,expirevar:IP.BLOCKED_1539=300,msg:'Rate limit of 2/60s exceeded for *, blocking IP %{REMOTE_ADDR} for 300s.'"
        - name: gf_simple_admin不允许
          source: inline
          path: ""
          rules:
            - 'SecRule REQUEST_URI "@beginsWith /admin" "id:63507,phase:1,deny,status:403,log,msg:''Simple Rule: Block directory /admin''"'
    default_action_body: 维护中，请稍后重试
