settings:
    log_directory: .
    ip_list_directory: ./ip_lists
    log:
        cleanup_by_time:
            enabled: false
            mode: days
            value: 7
        cleanup_by_lines:
            enabled: true
            retain_lines: 10
        cleanup_by_rule:
            ceshi2:
                enabled: false
                retain_lines: 1000
            ceshi3:
                enabled: false
                retain_lines: 1000
            ceshi5:
                enabled: false
                retain_lines: 1000
            ceshi8:
                enabled: false
                retain_lines: 1000
            test-all:
                enabled: false
                retain_lines: 1000
            test-tcp01:
                enabled: false
                retain_lines: 1000
            测试:
                enabled: false
                retain_lines: 1000
            测试1:
                enabled: false
                retain_lines: 1000
            测试4:
                enabled: false
                retain_lines: 1000
            端口转发:
                enabled: false
                retain_lines: 1000
global_access_control:
    mode: priority
    whitelist_enabled: true
    whitelist_list_name: 全局白名单
    blacklist_enabled: true
    blacklist_list_name: 全局黑名单
ip_lists:
    whitelists:
        全局白名单:
            - 192.168.122.250
    blacklists:
        全局黑名单:
            - 2.2.2.2
    ip_sets:
        ipv:
            - 192.168.122.250
    country_ip_lists:
        中国ip:
            type: country
            source: CN
    url_ip_sets:
        vn:
            type: url
            source: https://raw.githubusercontent.com/mayaxcn/china-ip-list/refs/heads/master/chn_ip.txt
rules:
    - name: test-all
      protocol: tcp,udp
      listen_addr: 0.0.0.0
      listen_port: 2223
      forward_addr: 192.168.122.250
      forward_port: 3389
      access_control:
        mode: disabled
        list_name: admin-ips
      enabled: true
      rate_limit: 20
    - name: test-tcp01
      protocol: udp
      listen_addr: ""
      listen_port: 53536
      forward_addr: 8.8.8.8
      forward_port: 53
      access_control:
        mode: disabled
        list_name: ""
      enabled: true
    - name: 端口转发
      protocol: tcp
      listen_addr: ""
      listen_port: 2225
      forward_addr: 192.168.122.250
      forward_port: 3389
      access_control:
        mode: disabled
        list_name: ""
      enabled: true
    - name: 测试
      protocol: tcp
      listen_addr: ""
      listen_port: 22226
      forward_addr: 192.168.122.250
      forward_port: 3389
      access_control:
        mode: disabled
        list_name: ""
      enabled: true
    - name: 测试1
      protocol: tcp
      listen_addr: ""
      listen_port: 2226
      forward_addr: 192.168.122.250
      forward_port: 80
      access_control:
        mode: disabled
        list_name: ""
      enabled: true
    - name: ceshi2
      protocol: tcp
      listen_addr: ""
      listen_port: 2227
      forward_addr: 192.168.122.250
      forward_port: 81
      access_control:
        mode: disabled
        list_name: ""
      enabled: true
    - name: ceshi3
      protocol: tcp
      listen_addr: ""
      listen_port: 2228
      forward_addr: 192.168.122.250
      forward_port: 9998
      access_control:
        mode: disabled
        list_name: ""
      enabled: true
    - name: 测试4
      protocol: tcp
      listen_addr: ""
      listen_port: 2229
      forward_addr: 192.168.122.250
      forward_port: 82
      access_control:
        mode: disabled
        list_name: ""
      enabled: true
    - name: ceshi5
      protocol: tcp
      listen_addr: ""
      listen_port: 2230
      forward_addr: 192.168.122.250
      forward_port: 3389
      access_control:
        mode: disabled
        list_name: ""
      enabled: true
    - name: ceshi8
      protocol: tcp
      listen_addr: ""
      listen_port: 22896
      forward_addr: 192.168.122.250
      forward_port: 308
      access_control:
        mode: disabled
        list_name: ""
      enabled: true
